/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paginainicial.ViewInicial;

/**
 *
 * @author FILIPE LIMA
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form ComprarPassagem
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Funcionario = new javax.swing.JButton();
        Veiculo = new javax.swing.JButton();
        Passagem = new javax.swing.JButton();
        Ajuda = new javax.swing.JButton();
        Rota1 = new javax.swing.JButton();
        Cidade1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Funcionario.setContentAreaFilled(false);
        Funcionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 240, 80));

        Veiculo.setContentAreaFilled(false);
        Veiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeiculoActionPerformed(evt);
            }
        });
        getContentPane().add(Veiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 240, 80));

        Passagem.setContentAreaFilled(false);
        Passagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Passagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassagemActionPerformed(evt);
            }
        });
        getContentPane().add(Passagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 240, 70));

        Ajuda.setContentAreaFilled(false);
        Ajuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjudaActionPerformed(evt);
            }
        });
        getContentPane().add(Ajuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 160, 60));

        Rota1.setContentAreaFilled(false);
        Rota1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rota1ActionPerformed(evt);
            }
        });
        getContentPane().add(Rota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 240, 70));

        Cidade1.setContentAreaFilled(false);
        Cidade1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cidade1ActionPerformed(evt);
            }
        });
        getContentPane().add(Cidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 610, 240, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Images/2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FuncionarioActionPerformed

    private void VeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VeiculoActionPerformed

    private void PassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassagemActionPerformed
        Passagem dialog = new Passagem(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_PassagemActionPerformed

    private void AjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjudaActionPerformed

    private void Rota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rota1ActionPerformed

    private void Cidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cidade1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajuda;
    private javax.swing.JButton Cidade1;
    private javax.swing.JButton Funcionario;
    private javax.swing.JButton Passagem;
    private javax.swing.JButton Rota1;
    private javax.swing.JButton Veiculo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
