/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package paginainicial.ViewInicial;

/**
 *
 * @author FILIPE LIMA
 */
public class Passagem extends javax.swing.JDialog {

    /**
     * Creates new form Passagem
     */
    public Passagem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputNome1 = new javax.swing.JTextField();
        InputHoraEmbarque = new javax.swing.JTextField();
        InputValorPassagem = new javax.swing.JTextField();
        InputCidadeOrigem = new javax.swing.JTextField();
        InputDestino = new javax.swing.JTextField();
        Confirmar = new javax.swing.JButton();
        InputPoltrona = new javax.swing.JTextField();
        InputCPF = new javax.swing.JTextField();
        InputDataEmbarque = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InputNome1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(InputNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 240, 52));

        InputHoraEmbarque.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(InputHoraEmbarque, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 240, 50));

        InputValorPassagem.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(InputValorPassagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 240, 50));

        InputCidadeOrigem.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(InputCidadeOrigem, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 240, 50));

        InputDestino.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(InputDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 240, 50));

        Confirmar.setContentAreaFilled(false);
        Confirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 160, 60));

        InputPoltrona.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(InputPoltrona, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 240, 50));

        InputCPF.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(InputCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 240, 50));

        InputDataEmbarque.setBackground(new java.awt.Color(255, 255, 255));
        InputDataEmbarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDataEmbarqueActionPerformed(evt);
            }
        });
        getContentPane().add(InputDataEmbarque, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 240, 50));

        Cancelar.setContentAreaFilled(false);
        Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Images/3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -40, 1090, 760));

        setSize(new java.awt.Dimension(982, 725));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed

    private void InputDataEmbarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDataEmbarqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDataEmbarqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Passagem dialog = new Passagem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Confirmar;
    private javax.swing.JTextField InputCPF;
    private javax.swing.JTextField InputCidadeOrigem;
    private javax.swing.JTextField InputDataEmbarque;
    private javax.swing.JTextField InputDestino;
    private javax.swing.JTextField InputHoraEmbarque;
    private javax.swing.JTextField InputNome1;
    private javax.swing.JTextField InputPoltrona;
    private javax.swing.JTextField InputValorPassagem;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
